// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: collector-app/collect.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CollectService_GetSingleCollectTime_FullMethodName  = "/senseauto.apcloud.app.collectorapp.v1.CollectService/GetSingleCollectTime"
	CollectService_GetSingleCollectMiles_FullMethodName = "/senseauto.apcloud.app.collectorapp.v1.CollectService/GetSingleCollectMiles"
	CollectService_GetCollectMiles_FullMethodName       = "/senseauto.apcloud.app.collectorapp.v1.CollectService/GetCollectMiles"
	CollectService_GetCollectTime_FullMethodName        = "/senseauto.apcloud.app.collectorapp.v1.CollectService/GetCollectTime"
)

// CollectServiceClient is the client API for CollectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectServiceClient interface {
	// 查询单车单日采集数据时长
	GetSingleCollectTime(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error)
	// 查询单车单日采集数据里程
	GetSingleCollectMiles(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error)
	// 查询车辆路测采集里程
	GetCollectMiles(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error)
	// 查询车辆路测采集时长
	GetCollectTime(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error)
}

type collectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectServiceClient(cc grpc.ClientConnInterface) CollectServiceClient {
	return &collectServiceClient{cc}
}

func (c *collectServiceClient) GetSingleCollectTime(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error) {
	out := new(GetIndicatorResponse)
	err := c.cc.Invoke(ctx, CollectService_GetSingleCollectTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectServiceClient) GetSingleCollectMiles(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error) {
	out := new(GetIndicatorResponse)
	err := c.cc.Invoke(ctx, CollectService_GetSingleCollectMiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectServiceClient) GetCollectMiles(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error) {
	out := new(GetIndicatorResponse)
	err := c.cc.Invoke(ctx, CollectService_GetCollectMiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectServiceClient) GetCollectTime(ctx context.Context, in *GetIndicatorRequest, opts ...grpc.CallOption) (*GetIndicatorResponse, error) {
	out := new(GetIndicatorResponse)
	err := c.cc.Invoke(ctx, CollectService_GetCollectTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectServiceServer is the server API for CollectService service.
// All implementations must embed UnimplementedCollectServiceServer
// for forward compatibility
type CollectServiceServer interface {
	// 查询单车单日采集数据时长
	GetSingleCollectTime(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	// 查询单车单日采集数据里程
	GetSingleCollectMiles(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	// 查询车辆路测采集里程
	GetCollectMiles(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	// 查询车辆路测采集时长
	GetCollectTime(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	mustEmbedUnimplementedCollectServiceServer()
}

// UnimplementedCollectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectServiceServer struct {
}

func (UnimplementedCollectServiceServer) GetSingleCollectTime(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleCollectTime not implemented")
}
func (UnimplementedCollectServiceServer) GetSingleCollectMiles(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleCollectMiles not implemented")
}
func (UnimplementedCollectServiceServer) GetCollectMiles(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectMiles not implemented")
}
func (UnimplementedCollectServiceServer) GetCollectTime(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectTime not implemented")
}
func (UnimplementedCollectServiceServer) mustEmbedUnimplementedCollectServiceServer() {}

// UnsafeCollectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectServiceServer will
// result in compilation errors.
type UnsafeCollectServiceServer interface {
	mustEmbedUnimplementedCollectServiceServer()
}

func RegisterCollectServiceServer(s grpc.ServiceRegistrar, srv CollectServiceServer) {
	s.RegisterService(&CollectService_ServiceDesc, srv)
}

func _CollectService_GetSingleCollectTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServiceServer).GetSingleCollectTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectService_GetSingleCollectTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServiceServer).GetSingleCollectTime(ctx, req.(*GetIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectService_GetSingleCollectMiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServiceServer).GetSingleCollectMiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectService_GetSingleCollectMiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServiceServer).GetSingleCollectMiles(ctx, req.(*GetIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectService_GetCollectMiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServiceServer).GetCollectMiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectService_GetCollectMiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServiceServer).GetCollectMiles(ctx, req.(*GetIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectService_GetCollectTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServiceServer).GetCollectTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectService_GetCollectTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServiceServer).GetCollectTime(ctx, req.(*GetIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectService_ServiceDesc is the grpc.ServiceDesc for CollectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "senseauto.apcloud.app.collectorapp.v1.CollectService",
	HandlerType: (*CollectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSingleCollectTime",
			Handler:    _CollectService_GetSingleCollectTime_Handler,
		},
		{
			MethodName: "GetSingleCollectMiles",
			Handler:    _CollectService_GetSingleCollectMiles_Handler,
		},
		{
			MethodName: "GetCollectMiles",
			Handler:    _CollectService_GetCollectMiles_Handler,
		},
		{
			MethodName: "GetCollectTime",
			Handler:    _CollectService_GetCollectTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collector-app/collect.proto",
}
